- internal/services/configstore/readdb/readdb.go
- internal/services/runservice/readdb/readdb.go
In runservice readdb Run method we could end with a deadlock if two of the
goroutines that call HandleEvents.* try to write to the errCh at the same
time before the errCh is read. If this happens one of the two will be blocked on
writing to the channel but the read won't happen since it'll blocked by
wg.Wait().
Fix this doing:
* use a buffered channel large as the number of executed goroutines.
* create a new errCh at every loop (so we'll ignore later errors after the first
one)
Note: we could also use a non blocking send to avoid this situation but we
should also start the wg.Wait before the goroutines or earlier errors could be
lost causing another kind of hang.
> readdb: fix deadlock in Run method

- internal/db/create.go
- internal/db/db.go
- internal/services/configstore/action/org.go
- internal/services/configstore/action/project.go
- internal/services/configstore/action/projectgroup.go
- internal/services/configstore/action/remotesource.go
- internal/services/configstore/action/secret.go
- internal/services/configstore/action/user.go
- internal/services/configstore/action/variable.go
- internal/services/configstore/api/org.go
- internal/services/configstore/api/project.go
- internal/services/configstore/api/projectgroup.go
- internal/services/configstore/api/remotesource.go
- internal/services/configstore/api/secret.go
- internal/services/configstore/api/user.go
- internal/services/configstore/api/variable.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/readdb/readdb.go
- internal/services/configstore/readdb/remotesource.go
- internal/services/gateway/gateway.go
- internal/services/runservice/action/action.go
- internal/services/runservice/api/api.go
- internal/services/runservice/readdb/readdb.go
Use the go sql context functions (ExecContext, QueryContext etc...)
The context is saved inside Tx so the library users should only pass it one time
to the db.Do function.
> db: use context functions

- internal/datamanager/changes.go
- internal/datamanager/datamanager.go
- internal/datamanager/wal.go
- internal/services/configstore/readdb/readdb.go
- internal/services/executor/executor.go
- internal/services/notification/runevents.go
- internal/services/runservice/readdb/readdb.go
- internal/services/runservice/runservice.go
- internal/services/runservice/scheduler.go
- internal/services/scheduler/scheduler.go
So we'll react instantly to a context cancel instead of waiting on time.Sleep
returning.
> *: use sleep timer in loops

- internal/services/configstore/action/action.go
- internal/services/configstore/action/maintenance.go
- internal/services/configstore/api/maintenance.go
- internal/services/configstore/common/common.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/util/goroutine.go
Implement configstore maintenance mode and export/import.
When configstore is set in maintenance mode it'll start only the maintenance and
export/import handlers.
Setting maintenance mode will set a key in etcd so all the configstore instances
will detect it and enter in maintenance mode. This is done asyncronously so it
could take some time (future improvements will add some api to show all the
configstore states)
Export is always available and will export the datamanager contents.
Import is available only during maintenance, given a datamanager export will
import it and reset etcd to this import state.
> configstore: maintenance/export/import

- internal/services/runservice/action/action.go
- internal/services/runservice/action/maintenance.go
- internal/services/runservice/api/maintenance.go
- internal/services/runservice/common/common.go
- internal/services/runservice/runservice.go
Implement runservice maintenance mode and export/import.
When runservice is set in maintenance mode it'll start only the maintenance and
export/import handlers.
Setting maintenance mode will set a key in etcd so all the runservice instances
will detect it and enter in maintenance mode. This is done asyncronously so it
could take some time (future improvements will add some api to show all the
runservice states)
Export is always available and will export the datamanager contents. Currently
only datamanager contents are exported (no logs and workspace archives).
Import is available only during maintenance, given a datamanager export will
import it and reset etcd to this import state.
> runservice: maintenance/export/import

- internal/services/runservice/action/action.go
- internal/services/runservice/scheduler.go
* Don't fail tasks inside the delete executor action, just delete the executor
from etcd
* The scheduler, when detecting a task without a related executor will mark the
task as failed and correctly set end time of the task and its steps.
> runservice: fix/improve executor delete logic

- internal/services/executor/executor.go
There was a typo so we weren't setting the task endTime when the setup step
failed.
Also unify all logic to just use `et` (instead of a mix of `et` or `rt.et`)
> executor: fix typo in setting task endTime when setup failed

- internal/services/executor/executor.go
Add missing set of task endTime when the executor is marking the task as failed
due to no related running task (usually after executor restart).
> executor: set task endTime when marking as failed

- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
Older version of docker doesn't support the exec api Env and WorkingDir options.
Support these versions by doing the same we already do with the k8s driver: use
the `toolbox exec` command that will set the provided Env, change the cwd to the
WorkingDir and the exec the wanted command.
> docker driver: use toolbox exec

- internal/services/executor/driver/docker.go
Set the client required api version to 1.26. In this way we'll work with docker >= 1.13.1
> docker driver: use fixed client api version

- .agola/config.jsonnet
- cmd/agola/cmd/directrunstart.go
- internal/gitsources/agolagit/agolagit.go
- internal/gitsources/gitea/gitea.go
- internal/gitsources/github/github.go
- internal/gitsources/gitlab/gitlab.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/user.go
- services/gateway/api/types/user.go
- tests/setup_test.go
Allow setting the destination branch/tag/ref so users can test the run
conditions based on the branch/tag/ref.
To simulate a pull request an user can define a ref that matches one of these
regular expressions: `refs/pull/(\d+)/head`, `refs/merge-requests/(\d+)/head`
> userdirectrun: allow setting destination branch/tag/ref

- doc/devel.md
"toolbox-path" flag is not available in "serve" command:
```
$ ./bin/agola serve --toolbox-path $PWD/bin/agola-toolbox --embedded-etcd --embedded-etcd-data-dir /tmp/etcd --config /data/agola/config.yml --components all-base,executor
Error: unknown flag: --toolbox-path
Usage:
agola serve [flags]
Flags:
--components strings              list of components to start. Specify "all-base" to start all base components (excluding the executor).
--config string                   config file path (default "./config.yml")
--embedded-etcd                   start and use an embedded etcd, only for testing purpose
--embedded-etcd-data-dir string   embedded etcd data dir, only for testing purpose (default "/tmp/agola/etcd")
-h, --help                            help for serve
--version …
```
> update example in devel doc

- cmd/agola/cmd/projectvariablecreate.go
- cmd/agola/cmd/projectvariableupdate.go
- internal/services/executor/driver/docker_test.go
- internal/services/gateway/api/variable.go
In c1ff28ef9f we exported various types. Unfortunately the types used by cmd
variable create/update are the wrong types and marshalling fails. Fix it using
the right type. In future this internal types should be exported.
> cmd: fix variable create/update

- internal/testutil/utils.go
- tests/setup_test.go
Add a function to wait for a specific condition instead of sleeping for a fixed
number of seconds.
> tests: add wait function in place of sleep

- internal/services/runservice/scheduler.go
Currently `advanceRunTasks` isn't deterministic and doesn't calculate the final
state in one call. So could happen that `getTasksToRun` will select a task to be
executed since its parent are finished (marked as skipped in advanceRunTasks)
but the task isn't marked to be skipped (because advanceRunTasks has calculated
this task before its parents).
Currently fix this doing the same task selection logic done in `advanceRunTasks`
and add a TODO to make `advanceRunTasks` be deterministic by processing tasks by
their level (from level 0).
> runservice: fix get tasks to run

- internal/util/path.go
- internal/util/path_test.go
Fix PathList when a path ends with one or more slashes and add related tests.
> util: Fix PathList output when path ends with slashes

- internal/git-handler/handler.go
On a git process error don't write the error message to the response body since
it'll break the git protocol and don't try to write the status header (since it's not
possible as it was automatically written by the go http server before writing
the body).
Fixes #101
> gitserver: don't return http response/error when calling external git process

- .agola/config.jsonnet
- Dockerfile
- go.mod
* agola run: Remove go 1.11 and use go 1.12 and go 1.13 with debian buster image.
* Dockerfile: Use go 1.13 debian buster image.
> *: update to go 1.13

- internal/config/config.go
- internal/runconfig/runconfig.go
- internal/services/executor/executor.go
- services/runservice/types/types.go
Defining an option to override the user for a run step is too much fine grained
and, for consistency, will require to do the same also for the other steps
(clone, *workspace etc...).
Remove it since it's probably enough to define it at the task level.
> runservice: remove run step user

- internal/services/executor/executor.go
- internal/services/runservice/action/action.go
- internal/services/runservice/api/api.go
- internal/services/runservice/api/executor.go
- internal/services/runservice/common/common.go
- internal/services/runservice/runservice.go
- internal/services/runservice/scheduler.go
- internal/services/runservice/store/store.go
- services/runservice/types/types.go
Reorganize ExecutorTask to better distinguish between the task Spec and
the Status.
Split the task Spec in a sub part called ExecutorTaskSpecData that contains
tasks data that don't have to be saved in etcd because it contains data that can
be very big and can be generated starting from the run and the runconfig.
> runservice: don't save executor task data in etcd

- internal/services/gateway/action/run.go
- tests/setup_test.go
I've tried to fix issue #51 adding a new option (skip_message) at "run" level:
```
version: v0
runs:
- name: run01
skip_message: "[ci skip]"
tasks:
- name: task01
runtime:
type: pod
containers:
- image: busybox
- name: run02
tasks:
- name: task01
runtime:
type: pod
containers:
- image: busybox
```
if the commit message contains the string specified in skip_message, for instance "[ci skip] Update README", run01 will be skipped and only run02 will be processed.
> skip run with special commit

- internal/config/config.go
- internal/runconfig/runconfig.go
A try to fix issue #3 adding a new optional parameter ("options") in clone "step".
Example:
```
steps:
- clone:
options: "--recurse-submodules --depth 1"
```
> config: add clone options

- cmd/agola/cmd/projectgroupsecretlist.go
- cmd/agola/cmd/projectgroupvariablelist.go
- cmd/agola/cmd/projectsecretlist.go
- cmd/agola/cmd/projectvariablelist.go
- services/gateway/client/client.go
I added "list" subcommand to list secret/variable names for projectgroup/project:
```
$ agola projectgroup secret list --projectgroup "user/user01/PG" --token $TOKEN
2882c284-8441-47cc-afce-d3caff74ad3f: Name: pg-secret
$ agola projectgroup variable list --projectgroup "user/user01/PG" --token $TOKEN
6c8fb616-b179-400b-bb56-179b486e838d: Name: pgvar
$ agola project secret list --project "user/user01/agola-example-go" --token $TOKEN
b7c7e8e6-9373-4079-91a0-4a2e8c461a6c: Name: secret-svil
$ agola project variable list --project "user/user01/agola-example-go" --token $TOKEN
1242da30-57a9-4f66-a8c8-f8a799ff9da2: Name: var01
```
I found it useful to update or delete secret/variable objects without the need to use the WUI to get their names.
I took the output format (\<id\>: Name: \<name\>) …
> cli: add secret/variable list subcommand

- cmd/agola/cmd/projectgroupsecretcreate.go
- cmd/agola/cmd/projectgroupsecretupdate.go
- cmd/agola/cmd/projectgroupvariablecreate.go
- cmd/agola/cmd/projectgroupvariableupdate.go
- cmd/agola/cmd/projectlist.go
- cmd/agola/cmd/projectreconfig.go
- cmd/agola/cmd/projectsecretcreate.go
- cmd/agola/cmd/projectsecretupdate.go
- cmd/agola/cmd/projectvariablecreate.go
- cmd/agola/cmd/projectvariableupdate.go
Fixed typos (mainly missed brackets) in online help messages.
> cmd: fix typos in online help

- Makefile
"X" parameter in LD_FLAGS pointed to an non existing package so Version was always undefined:
```
$ agola --version
agola version No version defined at build time
```
Modified to use cmd package to get the correct output:
```
$ agola --version
agola version 1244973c5554d50c55f095fc45e63d3b7e0f74d3-dirty
```
> cmd: fix version output

- tests/setup_test.go
* retry gitea create admin user command until ready
* wait for gitea api to be ready
> tests: wait gitea ready

- cmd/agola/cmd/completion.go
- cmd/agola/cmd/completionbash.go
- cmd/agola/cmd/completionzsh.go
Added "completion" command to generate scripts for shell auto-completion (bash and zsh).
Example:
```
agola completion bash >/etc/bash_completion.d/agola
```
> cmd: add completion command

- cmd/agola/cmd/serve.go
- cmd/agola/cmd/version.go
- internal/services/gateway/action/version.go
- internal/services/gateway/api/version.go
- internal/services/gateway/gateway.go
- services/gateway/api/types/version.go
- services/gateway/client/client.go
Implementation of version endpoint and command (#33):
```
$ curl http://localhost:8000/api/v1alpha/version
{"service":"gateway","version":"6cdd5bb108b682f0bca5b1c8a86c90c066a7c09d-dirty"}
$ agola version
Gateway version:	6cdd5bb108b682f0bca5b1c8a86c90c066a7c09d-dirty
Client version: 	6cdd5bb108b682f0bca5b1c8a86c90c066a7c09d-dirty
```
> cmd: add version command

- internal/config/config.go
- internal/config/config_test.go
- internal/runconfig/runconfig.go
- internal/runconfig/runconfig_test.go
- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/driver.go
- internal/services/executor/driver/k8s.go
- internal/services/executor/driver/k8s_test.go
- internal/services/executor/executor.go
- services/runservice/types/types.go
* Add a generic container volume option that currently only support tmpfs. In
future it could be expanded to use of host volumes or other kind of volumes (if
supported by the underlying executor)
* Implement creation of tmpfs volumes in docker and k8s drivers.
> *: implement ability to add tmpfs volumes to containers

- internal/gitsources/gitea/parse.go
- internal/gitsources/github/parse.go
- internal/gitsources/gitlab/parse.go
We were passing the source branch name as the Branch value in the webhook data.
This patch will just delete this assignment. If in future it's needed let's add
it with a different name to not cause confusion.
> gitsources: don't set branch value when in a pull request

- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
If a container, managed by docker driver, was configured to mount more than one volume:
```
volumes:
- path: /mnt/vol1
tmpfs:
size: 1Gi
- path: /mnt/vol2
tmpfs:
size: 512Mi
```
the result was that only the last one (in this case /mnt/vol2) was correctly mounted.
> docker: mount multiple volumes

- cmd/agola/cmd/runcreate.go
Add a run create command to manually create a run providing the project ref, the
branch/tag/ref and an optional commit sha.
> cmd: add run create command

- internal/objectstorage/s3/s3.go
If size is specified limit reads to size bytes.
> objectstorage s3: use limitreader in write object

- internal/objectstorage/objectstorage.go
- internal/objectstorage/posix/posix.go
- internal/objectstorage/posixflat/posixflat.go
Use limitreader only when size is specified (greater or equal to 0).
When size is unknown (less than 0) limitreader will immediately return EOF
instead of writing the whole data.
> objectstorage posix: use limitreader only when size is specified.

- internal/objectstorage/posix/posix.go
- internal/objectstorage/posixflat/posixflat.go
- internal/objectstorage/s3/s3.go
- internal/objectstorage/types/types.go
Return object size in object info.
> objectstorage: return object size in objectinfo

- README.md
Changed the issue link on README.md to point the issue template page.
[ci skip]
> README: issue link points to templates

- internal/config/config.go
- internal/config/config_test.go
- internal/runconfig/runconfig.go
- internal/services/executor/executor.go
- services/runservice/types/types.go
A try to fix issue #1 adding "tty" option for run steps (default is true):
```
- run:
name: test tty
command: "ps -ef && lsof"
tty: false
```
> run config: add tty option for run steps

- internal/sequence/sequence.go
- internal/sequence/sequence_test.go
Add tests to sequence String() and Parse(string) methods.
> sequence: add tests for String and Parse methods

- internal/datamanager/data.go
- internal/datamanager/datamanager.go
When creating a datafile name make it start with the current data sequence. This
is useful in future to know which data sequence created a new data file.
> datamanager: add data sequence to data file name

- cmd/agola/cmd/serve.go
- internal/services/config/config.go
- internal/services/config/config_test.go
> services: check config only for enabled services

- internal/datamanager/data.go
- internal/datamanager/datamanager.go
- internal/datamanager/datamanager_test.go
- internal/datamanager/wal.go
keep the last n (now set to 3) data status files and remove all other data status
files and unneeded data files.
> datamanager: clean old data files

- internal/datamanager/wal.go
currently creating .checkpointed files in the ost isn't useful.
We already have the data snapshot that reports the last checkpointed wal.
> datamanager: don't create ost wal checkpointed files

- internal/datamanager/data.go
- internal/datamanager/wal.go
- internal/services/configstore/readdb/readdb.go
- internal/services/runservice/readdb/readdb.go
make ReadWal directly return a *WalHeader
> datamanager: refactor ReadWal

- internal/datamanager/data.go
- internal/datamanager/datamanager_test.go
- internal/datamanager/wal.go
- internal/objectstorage/objectstorage.go
- internal/objectstorage/posix.go
- internal/objectstorage/posixflat.go
- internal/objectstorage/s3.go
- internal/services/configstore/action/org.go
- internal/services/configstore/action/project.go
- internal/services/configstore/action/projectgroup.go
- internal/services/configstore/action/secret.go
- internal/services/configstore/action/user.go
- internal/services/configstore/api/api.go
- internal/services/configstore/api/org.go
- internal/services/configstore/api/remotesource.go
- internal/services/configstore/api/user.go
- internal/services/configstore/readdb/readdb.go
- internal/services/gateway/action/action.go
- internal/services/gateway/api/api.go
- internal/services/gateway/api/run.go
- internal/services/runservice/action/action.go
- internal/services/runservice/api/api.go
- internal/services/runservice/api/executor.go
- internal/services/runservice/common/common.go
- internal/services/runservice/readdb/readdb.go
- internal/services/runservice/scheduler.go
- internal/services/runservice/store/store.go
- internal/util/errors.go
* objectstorage: remove `types` package and move `ErrNotExist` in base package
* objectstorage: Implement .Is and add helper `IsErrNotExist` for `ErrNotExist`
* util: Rename `ErrNotFound` to `ErrNotExist`
* util: Add `IsErr*` helpers and use them in place of `errors.Is()`
* datamanager: add `ErrNoDataStatus` to report when there's not data status in ost
* runservice/common: remove `ErrNotExist` and use errors in util package
> *: improve error handling

- internal/services/configstore/readdb/readdb.go
- internal/services/runservice/readdb/readdb.go
Rename errCh to doneCh (error is not needed) and always send to it when one of
the HandleEvents functions exits (not only on error).
This will ensure that all the goroutines will be stopped also if one of them
returns without an error.
> readdb: improve HandleEvents goroutine exiting

- internal/datamanager/wal.go
- internal/etcd/mutex.go
- internal/services/notification/runevents.go
- internal/services/runservice/scheduler.go
etcd PR 11104 (https://github.com/etcd-io/etcd/pull/11104) implemented mutex
TryLock. Since it's only available in etcd master just copy relevant code and
add a TODO to remove it when updating the etcd client to a version implementing
TryLock.
Use TryLock everywhere where it'll be useful.
> *: use etcd mutex TryLock

- internal/services/runservice/common/common.go
- internal/services/runservice/scheduler.go
When fetching avoid concurrent fetches from multiple runservices using an etcd
mutex TryLock.
> runservice: use etcd mutex TryLock on fetching

- internal/services/runservice/api/api.go
* return errNotExist in readTaskLogs when the executor task doesn't exist: so
the client will receive a 404 instead of a 500 (since a generic error will be
mapped to a 500).
* Wrap the errNotExist returned by readTaskLogs with a new ErrNotExits reporting
"log doesn't exist"
> runservice: improve errors in logsHandler

- internal/services/executor/api.go
- internal/services/gateway/api/run.go
- internal/services/runservice/api/api.go
Explicitly write and flush the headers in the various services LogHandlers.
Currently the 200 response and the other headers will be automatically written
by the golang http implementation only when we send something in the body. But if
there's nothing to send (no logs yet written) the client will never receive the
headers and cannot know if the request was successful.
> *: write and flush header on log handlers

- internal/services/gateway/action/run.go
- internal/services/gateway/api/run.go
- internal/services/gateway/gateway.go
- internal/services/runservice/api/api.go
- internal/services/runservice/runservice.go
- services/gateway/client/client.go
- services/runservice/client/client.go
- tests/setup_test.go
A try to fix issue #41 for logs deletion.
> gateway/runservice: add api to delete step logs

- cmd/agola/cmd/projectupdate.go
Trying to modify the project visibility from CLI ended up with a new project name (and visibility did not change):
```
$ agola project  list --parent "user/user01" --token $TOKEN
xxxxxx: Name: test
$ agola project update --ref "user/user01/test" --visibility private --token $TOKEN
INFO    cmd/projectupdate.go:82 updating project
INFO    cmd/projectupdate.go:87 project test update, ID: xxxxxx
$ agola project  list --parent "user/user01" --token $TOKEN
xxxxx: Name: private
```
Fixed assigning the passed value to the req.Visibility field.
> cmd: fix project visibility switch

- services/gateway/client/client.go
- tests/setup_test.go
The method GetRunTask, implemented in the gateway client to check if the log exists or not, pointed to wrong URL returned always logArchived even if not found. 
Added a check to verify if the step number is invalid (in this case the log will not exist and logArchived will not checked).
> gateway: fix api used by GetRunTask

- cmd/agola/cmd/log.go
- cmd/agola/cmd/logdelete.go
- cmd/agola/cmd/logget.go
- services/gateway/client/client.go
- tests/setup_test.go
Added `log get` and `log delete` commands (#183 and https://talk.agola.io/t/cli-run-logs-management/59/2)
> cmd: add log get and delete subcommands

- cmd/agola/cmd/runlist.go
Added task details in the output of `agola run list`:
```
0000001et7q3m-000000000000h: Phase: finished, Result: success
TaskName: build go 1.13, Status: success
Step: 0, Name: Clone repository and checkout code, Type: run, Phase: success, ExitStatus: 0
Step: 1, Name: restore cache, Type: restore_cache, Phase: success
Step: 2, Name: build the program, Type: run, Phase: success, ExitStatus: 0
Step: 3, Name: save to workspace, Type: save_to_workspace, Phase: success
Step: 4, Name: save cache, Type: save_cache, Phase: success
Step: 5, Name: save cache, Type: save_cache, Phase: success
TaskName: run, Status: success
Step: 0, Name: restore workspace, Type: restore_workspace, Phase: success
Step: 1, Name: ./bin/agola-example-go, Type: run, Phase: success, ExitStatus: 0
```
> cmd: add details to run list

- cmd/agola/cmd/runlist.go
Add `TaskID` field to the `run list` output (this information can be used to get/delete logs with `--taskid` option):
```
0000001et7q3m-000000000000n: Phase: finished, Result: success
TaskName: build go 1.13, TaskID: e2590e10-ef22-4e38-b558-415ec5498957, Status: success
<...>
```
> cmd: add TaskID to run list output

- internal/datamanager/datamanager_test.go
It is causing some timeout errors since there can be another instance from
another test run in parallel started on the same port.
> datamanager tests: don't wait for etcd down

- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
- internal/services/executor/executor.go
Instead of doing the current hack of copying the agola toolbox inside the host
tmp dir (always done but only needed when running the executor inside a docker
container) that has different issues (like tmp file removal done by
tmpwatch/systemd-tmpfiles), use a solution similar to the k8s driver: for every
pod create a volume containing the agola-toolbox and remove it at pod removal.
We could also use a single "global" volume but we should handle cases like
volume removal (i.e. a docker volume prune command). So for now just create a
dedicated per pod volume.
> docker: create a toolbox volume for every pod

- cmd/agola/cmd/serve.go
- internal/datamanager/datamanager_test.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
- internal/services/executor/executor.go
- internal/services/gateway/gateway.go
- internal/services/gitserver/main.go
- internal/services/notification/notification.go
- internal/services/runservice/runservice.go
- internal/services/runservice/scheduler.go
- internal/services/scheduler/scheduler.go
- internal/testutil/utils.go
- tests/setup_test.go
During tests provide a zaptest Logger so all services output will be redirected
to golang testing logger.
When multiple services of the same type are provided add a unique name field to
distinguish them.
> tests: improve services logging

- internal/services/configstore/configstore_test.go
Add "cs3" as unique name for the third ConfigStore instance
> tests: add unique name for logs of the third ConfigStore instance

- cmd/agola/cmd/usertokencreate.go
`user token create` subcommand has a wrong help message:
```
$ agola user token --help
<...>
Available Commands:
create      create a user linkedaccount
delete      delete a user token
<...>
```
> cmd: fix token create help message

- doc/devel.md
We usually test and support the latest two major versions of Go like in the [Go
release policy](https://golang.org/doc/devel/release.html#policy).
> doc: document supported go versions.

- cmd/agola/cmd/projectcreate.go
- cmd/agola/cmd/projectupdate.go
- internal/gitsources/gitea/parse.go
- internal/gitsources/github/parse.go
- internal/gitsources/gitlab/parse.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/run.go
- internal/services/gateway/api/project.go
- internal/services/gateway/api/webhook.go
- internal/services/types/webhook.go
- services/configstore/types/types.go
- services/gateway/api/types/project.go
- tests/setup_test.go
Add boolean parameter  to choose if pass variables to runs even when triggered by PRs (option disabled by default):
`agola project [create|update] --pass-vars-to-pr=true <...>`
Fixes #38
> cmd: project option to disable passing variables to PR from forked repo

- Makefile
There's no test script. Full tests can be easily executed inside a local
running agola instance using an agola "direct run".
Single package tests can be executed using a manual go test invocation based on
the kind of package we want to test (since some of them require a running etcd,
a running docker, a running k8s cluster, a gitea binary etc...)
> makefile: remove test target

- internal/gitsources/github/github.go
we were always setting the public github url in the github client instead of the
provided api url.
> github: use the provided api url

- cmd/agola/cmd/remotesourcecreate.go
Use default public github api only if no api-url is provided.
Use default public github ssh host key only if the public github api url is
provided and no ssh host key is provided.
> cmd: remotesource create don't force github defaults

- internal/gitsources/gitea/gitea.go
- internal/gitsources/github/github.go
- internal/gitsources/gitlab/gitlab.go
Pass a custom http client set to skip tls verification if required to oauth2
calls.
> gitsources: handle skipverify also in oauth2 requests

- internal/services/gateway/gateway.go
- services/gateway/client/client.go
Move the various authentication apis to /api/v1alpha/auth since they should be
versioned like other apis.
> gateway: move authentication apis to /api/v1alpha/auth

- internal/services/runservice/scheduler.go
- internal/services/runservice/scheduler_test.go
Currently when a run is marked to stop we are going to stop currently running
tasks and then their childs will be marked as skipped.
But tasks not depending on a stopped task (root task or childs with a finished
parent) that are just waiting for an executor slot, will be scheduled when
there will be a free slot also if the run is marked to stop (and then the
scheduler will stop them after some seconds).
This patch will mark all not started tasks as skipped when the run is marked to
stop.
> runservice: mark not running tasks as skipped when run marked to stop

- internal/services/runservice/action/action.go
- internal/services/runservice/scheduler.go
- internal/services/runservice/scheduler_test.go
- internal/services/runservice/store/store.go
Since the executor only periodically updates its state we could end up
scheduling much more tasks than the executor ActiveTasksLimit. This will happen
in the case of many parallel tasks that can all start at the same time.
To avoid this also consider the executor tasks saved in etcd that represent
the real view of scheduled tasks.
> runservice: minimize scheduling of tasks that will be queued by the executor

- internal/services/executor/executor.go
In executeTask set the executor task and step phase to stop if task spec Stop is
true.
> executor: fix reporting of stopped tasks and steps

- internal/services/runservice/scheduler.go
- internal/services/runservice/scheduler_test.go
rename activeExecutorTasks to scheduledExecutorTasks and don't filter out
finished tasks.
In some logic we need all the scheduled tasks and not only the not finished
ones.
> runservice: use all scheduled tasks in scheduleRun

- internal/services/executor/executor.go
When a related runningTask doesn't exist and the executor task status is
running just report it as failed ignoring if it's marked to stop.
> executor: fix stopping of not running tasks

- internal/services/executor/driver/docker.go
- internal/services/executor/executor.go
Use a cancellable context to handle running task stop.
When the context is done the pod will be stopped.
> executor: use cancellable context in executetask

- internal/services/runservice/scheduler.go
updateRunTaskStatus should also accept transitions from not started to a
finished state like "success", "failed", "stopped" since we could miss some
status updates from the executor for many reasons.
> runservice: fix handling of wrong executortask status

- .github/ISSUE_TEMPLATE/config.yml
Add a config to disable blank issues and show a reference to the Agola community
forum.
> github: add issue templates config

- internal/services/runservice/scheduler.go
skip fetching of tasks with status skipped, not only tasks marked as skip.
This avoid many wrong an noisy logs of type "executor task with id taskid
doesn't exist. This shouldn't happen. Skipping fetching"
> runservice: correctly handle skipped tasks in fetcher

- internal/runconfig/runconfig.go
If for some reasons the ssh public key auth fails, avoid the clone step to block
during a git clone waiting for a password.
> runconfig: disable password authentication in clone step

- go.mod
- go.sum
- internal/config/config.go
- internal/config/jsonnet.go
- internal/config/starlark.go
- internal/config/starlark_test.go
- internal/services/gateway/action/run.go
- tests/setup_test.go
Handle `.agola/config.star` files in starlark config format.
To provide a context like done for jsonnet we require that the starlark agola
config file contains a main function that will receive a config context as a
dict.
We also had to implement our own json conversion from a starlark dict since go
starlark removed its own function.
> config: add starlark config support

- internal/services/gateway/handlers/webbundle.go
> add content-type header for /config.js

- examples/agolademo/config.yml
The git server needs to be accessed on localhost from the gateway and not from
the host's docker bridge address.
> example: fix gitserverURL in example config

- internal/services/executor/driver/docker.go
- internal/services/executor/registry/registry.go
Use the same logic of k8s and pull init image only when has the latest (or
empty) tag or it doesn't exist.
> executor/docker: pull init image only when needed

- internal/services/config/config.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
- tests/setup_test.go
Use "busybox:stable" as default init image name so it won't be checked/pulled
any time.
> executor: use busybox:stable as default init image

- internal/runconfig/runconfig.go
> add case statement for on_skipped

- internal/runconfig/runconfig_test.go
> runconfig: test task generation with on_skipped dependencies

- internal/services/config/config.go
- internal/services/gitserver/gitserver_test.go
- internal/services/gitserver/main.go
- internal/services/gitserver/repo-cleaner.go
- tests/setup_test.go
enhancement: automatic cleanup of old repos/branches
#FIX #29
> gitserver: add cleanup of old repos/branches

- cmd/agola/cmd/directrunstart.go
- go.mod
- go.sum
- internal/datamanager/data.go
- internal/datamanager/wal.go
- internal/git-save/save.go
- internal/services/configstore/action/org.go
- internal/services/configstore/action/project.go
- internal/services/configstore/action/projectgroup.go
- internal/services/configstore/action/remotesource.go
- internal/services/configstore/action/secret.go
- internal/services/configstore/action/user.go
- internal/services/configstore/action/variable.go
- internal/services/configstore/common/common.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s.go
- internal/services/executor/driver/k8s_test.go
- internal/services/executor/executor.go
- internal/testutil/utils.go
- internal/util/uuid.go
- internal/util/validation.go
Replace https://github.com/satori/go.uuid with maintained version at
https://github.com/gofrs/uuid
Since the new version uuid.NewV4 returns an error when failing to read
from the random source reader we use uuid.Must to panic on error since
it's considered an unrecoverable error.
In future, if needed, we could handle the error instead of panicking.
> go.mod: replace https://github.com/satori/go.uuid

- internal/services/gateway/action/auth.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/remotesource.go
- internal/services/gateway/action/run.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/org.go
- internal/services/gateway/api/projectgroup.go
- internal/services/gateway/api/remoterepo.go
- internal/services/gateway/api/user.go
- internal/services/gateway/common/common.go
- internal/services/gateway/handlers/auth.go
Use auth context keys dedicated type instead of strings and avoid code
duplication by moving shared code under a common package.
> gateway: use dedicated auth context keys type

- tests/setup_test.go
Avoid starting gitea for direct runs tests since it's not used.
> tests: don't start gitea for direct runs test

- cmd/agola/cmd/runlist.go
Fux run list panic on task with nil exit status.
It may happen that a finished task doesn't have an exit status.
> cmd: fix run list panic on task with nil exit status

- internal/datamanager/datamanager_test.go
- internal/objectstorage/objectstorage_test.go
- internal/objectstorage/posix_test.go
- internal/objectstorage/posixflat_test.go
- internal/services/config/config_test.go
- internal/services/configstore/configstore_test.go
- internal/services/gitserver/gitserver_test.go
- tests/setup_test.go
A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
~~**Note:** `T.TempDir` requires Go 1.15 or higher, hence the `go` directive in `go.mod` is bumped to `1.16` since the project has been updated to Go 1.16 in #257.~~
Reference: https://pkg.go.dev/testing#T.TempDir
> test: use `T.TempDir` to create temporary test directory

- internal/services/configstore/action/org.go
- internal/services/configstore/action/project.go
- internal/services/configstore/action/projectgroup.go
- internal/services/configstore/action/remotesource.go
- internal/services/configstore/action/secret.go
- internal/services/configstore/action/variable.go
- internal/services/configstore/api/org.go
- internal/services/configstore/api/project.go
- internal/services/configstore/api/projectgroup.go
- internal/services/configstore/api/remotesource.go
- internal/services/configstore/api/secret.go
- internal/services/configstore/api/variable.go
- internal/services/configstore/configstore_test.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/projectgroup.go
- internal/services/gateway/action/remotesource.go
- internal/services/gateway/action/secret.go
- internal/services/gateway/action/variable.go
- services/configstore/api/types/org.go
- services/configstore/api/types/project.go
- services/configstore/api/types/remotesource.go
- services/configstore/api/types/secret.go
- services/configstore/api/types/variable.go
- services/configstore/client/client.go
Don't directly use object types as request but dedicated request types.
> configstore: update api and action request types

- internal/runconfig/runconfig.go
Newer versions of openssh client disables ssh-rsa sha1 public key
signature algorithm.
Unfortunately gitea ssh server requires this signature algorithm instead
of using the stronger rsa-sha2-256/rsa-sha2-512 (see
https://github.com/go-gitea/gitea/issues/17798)
So, as a temporary workaround, force enable on the ssh client the
ssh-rsa sha1 signature algorithm.
That's the reason why tests on run.agola.io are failing.
The new alpine/git image has a new openssh version disabling such algo.
> runconfig: temporary enable ssh client ssh-rsa sha1 signature algorithm

- services/types/duration.go
- services/types/duration_test.go
Added Duration custom type for unmarshall json duration as human format  or nanoseconds
> types: add custom Duration type

- internal/services/config/config.go
Fix some tags that were marked as json instead of yaml.
> services config: correctly use yaml tags instead of json tags

- .agola/config.jsonnet
- Dockerfile
update dockerfile and agola config for using golang 1.18
> update to go 1.18

- internal/services/executor/executor.go
Unlock runningTask before calling setupTask
This is needed because setupTask can take much time and lock other routines
> executor: avoid locking during setupTask

- internal/services/config/config.go
- internal/services/runservice/common/common.go
- internal/services/runservice/runservice.go
- internal/services/runservice/runservice_test.go
- internal/services/runservice/scheduler.go
- internal/services/runservice/store/store.go
> runservice: added logcleanerLoop for deleting older logs

- internal/config/config.go
- internal/runconfig/runconfig.go
- internal/runconfig/runconfig_test.go
- internal/services/executor/executor.go
- internal/services/gateway/api/run.go
- internal/services/runservice/common/common.go
- internal/services/runservice/scheduler.go
- services/gateway/api/types/run.go
- services/runservice/types/executortask.go
- services/runservice/types/run.go
- services/runservice/types/runconfig.go
- tests/setup_test.go
fix #6 
runConfig: added TaskTimeout in global, run and task configuration
executor: added tasksTimeoutCleaner for managing task timeout
scheduler: updated executorTaskCleaner for managing task timeout and report it to the executor with a timeout signal in ExecutorTaskSpec
> runservice: add tasks timeout

- internal/gitsources/gitea/gitea.go
- internal/gitsources/github/github.go
- internal/gitsources/gitlab/gitlab.go
- internal/gitsources/gitsource.go
- internal/services/configstore/action/project.go
- internal/services/configstore/api/project.go
- internal/services/gateway/action/project.go
- internal/services/gateway/api/project.go
- internal/services/gateway/gateway.go
- services/configstore/api/types/project.go
- services/configstore/types/project.go
- services/gateway/api/types/project.go
- services/gateway/client/client.go
- tests/setup_test.go
fix #275
Added action GetRepoInfo to get repo info.
Updated gateway api to return default branch into type ProjectResponse
> Handle remote repo default branch

- internal/services/configstore/action/org.go
- tests/setup_test.go
The configstore action AddOrgMember actually use the db method InsertOrganizationMember, that return error when update an existing user member.
The method InsertOrUpdateOrganizationMember works for new and existing user member.
> configstore: fix action AddOrgMember

- internal/services/configstore/action/org.go
- internal/services/configstore/configstore_test.go
Use GetOrg method in DeleteOrg action to correctly get the org by both id and ref.
> configstore: use GetOrg method in DeleteOrg

- internal/services/config/config.go
- internal/services/configstore/action/org.go
- internal/services/configstore/action/projectgroup.go
- internal/services/configstore/action/user.go
- internal/services/configstore/api/org.go
- internal/services/configstore/api/user.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/configstore/db/fetch.go
- internal/services/configstore/db/insert_delete.go
- internal/services/configstore/db/objects/objects.go
- internal/services/configstore/db/qtables.go
- internal/services/gateway/action/action.go
- internal/services/gateway/action/auth.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/org.go
- internal/services/gateway/api/user.go
- internal/services/gateway/gateway.go
- services/configstore/api/types/invitation.go
- services/configstore/client/client.go
- services/configstore/types/invitation.go
- services/configstore/types/types.go
- services/gateway/api/types/invitation.go
- services/gateway/client/client.go
- tests/setup_test.go
FIX #42
This allow users owner to create invitation to an organization.
When create an invitation is is possible to choose the user role.
If the user accept the invitation he will be added to the organization with the specified role;
if he refuse the invitation will be deleted.
Add Invitation type with the following fields:
- UserID string 
- OrganizationID string
- Role MemberRole
- CreatorUserID string
- CreatedAt time.Time
The user owner can create an invitation with api:
POST /orgs/{orgref}/invitations
An user owner can get org invitations with api:
GET /orgs/{orgref}/invitations
The current user can give the invitations wiith api:
GET /user/invitations
The current user can accept or refuse the invitation, the user owner can cancel it with api:
PUT /invitations/{invitationid}/actions …
> *: implement org member adding modes: direct or invitation

- cmd/agola/cmd/userlist.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/user.go
- services/gateway/client/client.go
- tests/setup_test.go
fix #351
added /remotesources/{remotesourceref}/remoteuser/{remoteuserid} api to get user by remotesourceref and remoteuserid
> gateway: add admin api to get remote source user

- cmd/agola/cmd/export.go
- cmd/agola/cmd/import.go
- cmd/agola/cmd/maintenance.go
- cmd/agola/cmd/maintenancedisable.go
- cmd/agola/cmd/maintenanceenable.go
- internal/services/configstore/api/maintenance.go
- internal/services/configstore/configstore.go
- internal/services/gateway/action/maintenance.go
- internal/services/gateway/api/maintenance.go
- internal/services/gateway/gateway.go
- internal/services/runservice/runservice.go
- services/configstore/api/types/maintenance.go
- services/configstore/client/client.go
- services/gateway/api/types/maintenance.go
- services/gateway/client/client.go
- services/runservice/api/types/maintenance.go
- services/runservice/client/client.go
- tests/setup_test.go
fix #318
Agola commands added:
agola export  --service {configstore/runservice} --file-path {export-file-path}
agola import --service {configstore/runservice} --file-path {import-file-path}
agola maintenance --service {configstore/runservice}
> add cmd import, export, maintenance for runservice and configstore

- internal/util/errors.go
Fix empty APIError error message printing using standard fmt.Sprintf. This went unnoticed since we were always using zerolog for logging but in tests it may appear.
Since errors.Stack was embededded in APIError its Format method is used instead of the APIError.Error() method and when not using "%+v" it prints an empty string.
Fix this by not embedding errors.Stack and returning the stack by implementing the StackTracer interface.
> util: fix empty APIError error message printing

- internal/objectstorage/objectstorage.go
- internal/objectstorage/posix.go
- internal/objectstorage/posixflat.go
- internal/objectstorage/s3.go
- internal/services/configstore/configstore_test.go
- internal/util/errors.go
- internal/util/http.go
* Add a WrapperError helper type that can be embedded by custom errors to easily implement the stacktracing and wrapping ability.
* Make APIError and objectStorage.ErrNotExist use it.
> util: add wrapper error helper type

- internal/services/gateway/common/auth.go
- internal/services/gateway/gateway.go
- internal/services/gateway/handlers/authchecker.go
- tests/cookieclient_test.go
- tests/setup_test.go
* skip csrf check only on successful token auth and not only if the token has been provided.
* improve checkers logic to tell when auth should fail in the checker response so we could return an unauthorized error
> gateway: skip csrf check only on successful token auth

- internal/services/executor/api.go
- internal/services/executor/executor.go
- internal/services/runservice/action/action.go
- internal/services/runservice/api/executor.go
- internal/services/runservice/scheduler.go
- services/runservice/api/types/executor.go
- services/runservice/client/client.go
- services/runservice/types/executortask.go
Don't send/receive the internal executor types for communication with the executor but use dedicated api types.
> runservice: use dedicated api types for executor communication

- internal/services/executor/driver/k8s_test.go
The shell command to check if all the volumes where mounted was missing a check.
> executor: fix k8s test

- doc/migrating_from_v0.7.x.md
- internal/migration/248a9e0ad/configstore.go
- internal/migration/248a9e0ad/runservice.go
- internal/migration/v0.7.x/configstore.go
- internal/migration/v0.7.x/runservice.go
Entries could be out of order causing foreign keys constraints failures.
Defer foreign key validation at commit time.
Also fix migration doc typo.
> migrateexport: defer sqlite foreign keys

- internal/migration/destination/runservice/db/db.go
- internal/services/runservice/db/db.go
- tests/setup_test.go
Since the filters for run phase and result are slices, don't use sql "EQUAL" but "IN".
> runservice/db: fix get run query

- internal/gitsources/gitea/gitea.go
- internal/gitsources/github/github.go
- internal/gitsources/gitlab/gitlab.go
- internal/gitsources/gitsource.go
- internal/services/common/gitsource.go
- internal/services/gateway/action/user.go
Split an oauth2Client from the gitsource. While the gitsource creates a client to the remote source an Oauth2Client doesn't requires a client to the remote sources but only handles the oauth2 flow.
This also fixes an issue with gitea 1.14 (fixed in later gitea versions) where the /version endpoint requires authentication but during the oauth2 flow we don't have any auth data and so we cannot create the gitea client because during gite client creation a call to the version endpoint is done and returns an error.
> gitsources: split oauth2Client from gitsource

- internal/services/gateway/action/user.go
Pass userRef instead of linked account RemoteUserName to GetGitSource
> gateway: fix GetUserGitSource action

- internal/services/config/config.go
- internal/services/config/config_test.go
Use a function to return a fixed default config to avoid updating it during parse.
Fix tests related to this fix.
> config: avoid updating the default config

- internal/services/config/config.go
- internal/services/config/config_test.go
Add global url fields that will be used by all the services (when not defined in the service config)
This avoids repeating them for every service.
> config: add global urls fields

- internal/services/config/config.go
- internal/services/config/config_test.go
- internal/services/configstore/configstore.go
- internal/services/executor/executor.go
- internal/services/gateway/api/repos.go
- internal/services/gateway/gateway.go
- internal/services/gitserver/main.go
- internal/services/handlers/auth.go
- internal/services/notification/notification.go
- internal/services/runservice/runservice.go
- internal/services/runservice/scheduler.go
- internal/services/scheduler/scheduler.go
- services/common/client.go
- services/configstore/client/client.go
- services/runservice/client/client.go
- tests/setup_test.go
Add optional internal services authentication using an api token defined in the configuration.
If the service hasn't defined an api token then no authentication check is done.
> *: Optional internal services authentication

- internal/sqlg/object.go
A field can be defined as a byte array by defining the type []byte. This will set the sqlType to "bytea" for postgres and "blob" for sqlite3.
> sqlg: add support for blob/byte array base type

- internal/testutil/db.go
Handle column of type byte array that can be defined providing the base64 encoding of the data.
> testutils/db: handle byte array

- tests/setup_test.go
use a const instead of repeating the same string multiple times.
> tests: use const for remote error string output

- cmd/agola/cmd/logget.go
- cmd/agola/cmd/orgmemberlist.go
- go.mod
- go.sum
- internal/services/configstore/action/org.go
- internal/services/configstore/api/api.go
- internal/services/configstore/api/org.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/gateway/action/action.go
- internal/services/gateway/action/auth.go
- internal/services/gateway/action/cursor.go
- internal/services/gateway/action/maintenance.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/run.go
- internal/services/gateway/api/api.go
- internal/services/gateway/api/org.go
- internal/services/gateway/gateway.go
- services/common/client.go
- services/configstore/client/client.go
- services/configstore/types/types.go
- services/gateway/api/types/types.go
- services/gateway/client/client.go
- services/runservice/client/client.go
- tests/setup_test.go
This commit adds code required to implement cursor based list apis.
It also changes the first list api (GetOrgMembers).
These api changes are breaking changes, so a related change in the agola
web repository is required and should be merged together.
Some implementation notes:
* Only the gateway list APIs use opaque cursors.
* The cursor is provided as a custom X-Agola-Cursor response header.
* The provided cursor will be for the next batch of result
using the same query options of the first call (limit excluded).
* When a cursor is provided all the other query options cannot be
provided with the exception of limit.
* A default limit is forced if not provided.
* The underlying services (configstore, runservice) will continue using
explicit list options (start, sort etc...) based api …
> *: cursor based list api.

- .agola/config.jsonnet
Test were failing due to exceeding the default max number of connections. Increase the postgres max connections to 300.
> ci: increase postgres container max connections

- internal/testutil/db.go
When importing, use sequences provided by create data and not the db struct sequences since they are the latest db version sequences and could be different.
> testutils/db: use sequences provided by create data during import

- cmd/agola/cmd/remotesourcelist.go
- internal/services/configstore/action/remotesource.go
- internal/services/configstore/api/remotesource.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/gateway/action/remotesource.go
- internal/services/gateway/api/remotesource.go
- services/configstore/client/client.go
- services/gateway/client/client.go
- tests/setup_test.go
Add cursor fetching to GetRemoteSources api.
> *: add cursor fetching to GetRemoteSources api

- internal/services/gateway/action/auth.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/projectgroup.go
- internal/services/gateway/action/run.go
- internal/services/gateway/action/secret.go
- internal/services/gateway/action/variable.go
- services/gateway/client/client.go
- tests/setup_test.go
Like already done for projects, check if user can see the org/pg by
checking the visibility and user membership.
Add various integration tests to check multiple org/pg/project
visibility combinations.
> gateway: correctly handle org/pg visibility

- internal/testutil/db.go
When exporting, use schema provided by migrate data and not the create data since the migration change the db shema to the migrate version.
> testutils/db: use schema provided by migrate data during export

- internal/testutil/db.go
Since we are retrieving any type from the db rows.Scan we should handle the possible returned types for a bool col type. Currently handle booleans, int64 0 or 1, uint8[] of chars making a string of value "true" or "false".
> testutils/db: handle col type bool on export

- .agola/config.jsonnet
- Dockerfile
- go.mod
- go.sum
- internal/sqlg/sql/db_test.go
- internal/testutil/db.go
* Also update go.mod version to latest supported version: go 1.20. This is enforced starting from go 1.21 (https://go.dev/ref/mod#go-mod-file-go).
* Also update golangci-lint to v1.54.2
* Remove not needed rand.Seed in packages (already seeded randomly starting from go 1.20)
> *: update to go 1.21

- internal/services/runservice/api/api.go
- tests/setup_test.go
A missing return after nil run check caused the return of a wrong error.
Fix this by moving the logic to a dedicated function instead of doing everything in ServeHTTP.
> runservice: return right error on not existing run

- internal/services/configstore/configstore_test.go
fix test get remotesources continuation since it is not checking the responses fetched in continuation cycle.
> configstore: fix test get remotesources continuation

- internal/services/gateway/action/runwebhookdelivery.go
- internal/services/gateway/api/runwebhookdelivery.go
- internal/services/gateway/gateway.go
- internal/services/notification/action/runwebhookdelivery.go
- internal/services/notification/api/runwebhookdelivery.go
- internal/services/notification/db/db.go
- internal/services/notification/notification.go
- internal/services/notification/notification_test.go
- services/gateway/client/client.go
- services/notification/client/client.go
- tests/setup_test.go
This patch adds an api to redelivery a run webhook delivery by project ref and run webhook delivery id.
fix #424
> gateway: add api to redelivery a run webhook delivery

- internal/services/notification/notification_test.go
Also don't log 'starting ns' since notification service isn't really started.
> notification: remove time.sleep from tests

- internal/services/configstore/action/action.go
- internal/services/configstore/action/maintenance.go
- internal/services/configstore/api/maintenance.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
Rework maintenance mode logic refactoring some variable names and exposing an action handler method to get current maintenance mode.
> configstore: remove time.sleep from tests

- internal/services/runservice/action/action.go
- internal/services/runservice/action/maintenance.go
- internal/services/runservice/api/maintenance.go
- internal/services/runservice/runservice.go
- internal/services/runservice/runservice_test.go
Rework maintenance mode logic refactoring some variable names and exposing an action handler method to get current maintenance mode.
> runservice: remove time.sleep from tests

- internal/services/gateway/action/commitstatusdelivery.go
- internal/services/gateway/api/commitstatusdelivery.go
- internal/services/gateway/gateway.go
- internal/services/notification/action/commitstatusdelivery.go
- internal/services/notification/api/commitstatusdelivery.go
- internal/services/notification/commitstatusdelivery.go
- internal/services/notification/db/db.go
- internal/services/notification/notification.go
- internal/services/notification/notification_test.go
- services/gateway/api/types/commitstatusdelivery.go
- services/gateway/client/client.go
- services/notification/client/client.go
- tests/setup_test.go
This patch adds an api to get commit status deliveries by project ref.
> gateway: add api to get commit status deliveries

- internal/services/notification/db/db.go
- internal/services/notification/notification_test.go
Rename function GetProjectRunWebhookDeliveriesAfterSequence to GetRunWebhookDeliveriesAfterSequence since it doesn't filter by project.
> notification: rename GetProjectRunWebhookDeliveriesAfterSequence func

- internal/testutil/log.go
Read from the DETAILED_ERRORS env var and if true enable detailed errors for zerolog logging in tests.
Also use zerolog provided TestWriter.
> testutil: add detailed errors for zerolog output in tests

- internal/config/config_test.go
- internal/objectstorage/objectstorage_test.go
- internal/objectstorage/posix_test.go
- internal/objectstorage/posixflat_test.go
- internal/services/config/config_test.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/tests/migrate_test.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
- internal/services/gitserver/gitserver_test.go
- internal/services/notification/db/tests/migrate_test.go
- internal/services/notification/notification_test.go
- internal/services/notification/runeventssender_test.go
- internal/services/notification/webhooksreceiver_test.go
- internal/services/runservice/db/tests/migrate_test.go
- internal/services/runservice/runservice_test.go
- internal/services/runservice/scheduler_test.go
- internal/sqlg/sql/db_test.go
- internal/testutil/db.go
- internal/testutil/log.go
- internal/testutil/utils.go
- internal/util/path_test.go
- internal/util/slice_test.go
- internal/util/validation_test.go
- tests/setup_test.go
- tests/webhooksreceiver.go
Add a NilError helper based on assert.NilError that will log detailed
test errors when DETAILED_ERRORS env var is true.
Use this function in all tests.
> testutil: Add NilError helper to log detailed test errors

- internal/services/notification/db/db.go
- internal/services/notification/notification_test.go
fix db func GetProjectCommitStatusDeliveriesAfterSequenceByProjectID since startSequence is not provided when the client ask by the first commit status delivery.
> notification: fix db func GetProjectCommitStatusDeliveriesAfterSequenceByProjectID

- internal/services/notification/db/db.go
- internal/services/notification/notification_test.go
fix db func GetProjectRunWebhookDeliveriesAfterSequenceByProjectID since startSequence is not provided when the client ask by the first run webhook delivery.
> notification: fix db func GetProjectRunWebhookDeliveriesAfterSequenceByProjectID

- internal/services/gateway/action/commitstatusdelivery.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/remotesource.go
- internal/services/gateway/action/runwebhookdelivery.go
- internal/services/gateway/action/user.go
- tests/setup_test.go
add setting of sort direction to the out cursors.
> gateway: fix api cursors

- internal/services/gateway/action/commitstatusdelivery.go
- internal/services/gateway/api/commitstatusdelivery.go
- internal/services/gateway/gateway.go
- internal/services/notification/action/commitstatusdelivery.go
- internal/services/notification/api/commitstatusdelivery.go
- internal/services/notification/db/db.go
- internal/services/notification/notification.go
- internal/services/notification/notification_test.go
- services/gateway/client/client.go
- services/notification/client/client.go
- tests/setup_test.go
This patch adds an api to redeliver a commit status delivery by project ref and commit status delivery id.
> gateway: add api to redeliver a commit status delivery

- internal/services/runservice/common/common.go
- tests/setup_test.go
add AGOLA_RUN_COUNTER variable by default with run counter value to the run environment
fix #362
> runservice: add AGOLA_RUN_COUNTER variable

- tests/setup_test.go
Just use a loop instead of a starting call and then loop for next calls with cursor.
Also use right deepequal parameters order (first expected, second got).
> tests: simplify Get API with cursor tests

- internal/services/gateway/action/commitstatusdelivery.go
- internal/services/gateway/action/cursor.go
- internal/services/gateway/action/runwebhookdelivery.go
- internal/services/gateway/api/commitstatusdelivery.go
- internal/services/gateway/api/runwebhookdelivery.go
- services/gateway/client/client.go
- tests/setup_test.go
The api filter options should be saved inside the cursor.
Also check that not both cursor and filter query parameter are provided.
> *: commitstatus/runwebook delivery save filter inside cursor

- internal/services/configstore/action/org.go
- internal/services/configstore/action/remotesource.go
- internal/services/configstore/action/user.go
- internal/services/configstore/configstore_test.go
- internal/services/gateway/action/commitstatusdelivery.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/remotesource.go
- internal/services/gateway/action/runwebhookdelivery.go
- internal/services/gateway/action/user.go
- internal/services/notification/action/commitstatusdelivery.go
- internal/services/notification/action/runwebhookdelivery.go
- internal/services/notification/notification_test.go
- services/configstore/client/client.go
- services/notification/client/client.go
- tests/setup_test.go
For all the services, both underlying services and the gateway, ensure a default sort direction is provided and so also used in the returned cursor.
Not having a default sort direction could lead to unpredictable results between calls depending on the underlying database.
> *: actions: ensure a default sort direction

- internal/services/notification/commitstatus.go
- internal/services/notification/commitstatusdelivery.go
- internal/services/notification/notification_test.go
- internal/services/notification/runwebhookdelivery.go
- internal/services/notification/webhooks.go
The variable holding the next starting id was defined inside the loop instead than outside.
Improve tests to trigger multiple loops
> notification: fix cleaners infinite loop.

- internal/services/config/config.go
- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s.go
- internal/services/executor/executor.go
* Add an option to define the network the docker driver will use when creating containers. The network should already exist.
* Use option pattern to avoid adding too many parameters to the constructor functions.
> executor: add option to define docker driver network

- Dockerfile
- examples/agolademo/README.md
- examples/agolademo/agola/config.yml
- examples/agolademo/docker-compose.yml
- examples/agolademo/gitea/app.ini
Improve the agola demo by using docker compose:
* Use a dedicated bridged network
* Adapt the agola and gitea config for the new setup
* Also add a README.md (with the same contents of the tryit
documentation on the agola site, that will be updated).
> agolademo: use docker compose

- .agola/config.jsonnet
- Dockerfile
- cmd/agola/cmd/runlist.go
- cmd/agola/cmd/serve.go
- go.mod
- go.sum
- internal/runconfig/runconfig_test.go
- internal/services/config/config.go
- internal/services/configstore/configstore_test.go
- internal/services/executor/driver/docker.go
- internal/services/gateway/api/user.go
- internal/services/notification/notification_test.go
- internal/services/notification/runeventssender_test.go
- internal/services/runservice/common/common.go
- internal/services/runservice/runservice_test.go
- internal/services/runservice/scheduler_test.go
- internal/testutil/db.go
- internal/util/errors.go
- internal/util/slice.go
- internal/util/slice_test.go
- tests/api_test.go
* go.mod use go 1.21 minimum version semantics.
* ci: use the current last two go versions: 1.21 and 1.22
* Dockerfile: use go 1.22 image
* replace util.StringInSlice with slices.Contains generic function.
* rename util.CompareStringSlice and util.CompareStringSliceNoOrder util util.EqualStringSlice... and use internally use slices.Equal generic function.
* use slices package sort functions instead of sort package ones.
> *: update to go 1.22

- internal/util/validation.go
- internal/util/validation_test.go
* Accept names from 1 to 40 runes (utf-8 characters) length.
* For single char names use a dedicated validation regexp that accept only one digit or ascii char.
> validation: add min/max length check to name validation

- cmd/agola/cmd/export.go
close the created file descriptor at the end of the export function.
> cmd/export: close file descriptor

- internal/services/gateway/action/org.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/projectgroup.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/org.go
- internal/services/gateway/api/projectgroup.go
- internal/services/gateway/api/remoterepo.go
- internal/services/gateway/api/user.go
There were few api handlers that fetched the current user and passed it to the actions. Move this in the right place directly inside the actions.
> gateway: move remaining get of current user from api to action

- internal/services/gateway/action/org.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/run.go
- internal/services/gateway/action/user.go
- tests/auth_test.go
Auth check returning an Unauthenticated (http 401) error must be performed by the auth checker. In the action we assume it's done and in case of missing auth user we return a Forbidden error (http 403).
> gateway: unify/improve handling of authenticated user

- internal/services/config/config.go
Check that the provided sqlite3 db connstring is an absolute file path.
> services/config: check valid sqlite3 db connstring

- internal/objectstorage/objectstorage.go
- internal/util/errors.go
Currently WithWrapperErrorMsg wants a format and args like fmt.Sprintf but new go vet checks for non-constant format string in calls so it cannot be used for dynamic messages.
Fix this by renaming WithWrapperErrorMsg to WithWrapperErrorMsgf and adding WithWrapperErrorMsg that uses fmt.Sprint .
> errors: add WithWrapperErrorMsgf

- .agola/config.jsonnet
- Dockerfile
- go.mod
- internal/util/dump.go
* go.mod use go 1.22 minimum version semantics.
* ci: use the current last two go versions: 1.22 and 1.23
* Dockerfile: use go 1.23 image
> *: update to go 1.23

- .agola/config.jsonnet
- .golangci.yml
- cmd/agola/cmd/runlist.go
- internal/gitsources/gitea/parse.go
- internal/gitsources/github/github.go
- internal/gitsources/github/parse.go
- internal/gitsources/gitlab/parse.go
- internal/migration/destination/runservice/db/db.go
- internal/objectstorage/atomic.go
- internal/objectstorage/posix.go
- internal/services/executor/executor.go
- internal/services/gateway/api/user.go
- internal/services/notification/runeventssender_test.go
- internal/services/runservice/api/api.go
- internal/services/runservice/db/db.go
- internal/sqlg/gen/gen_ddl.go
- internal/sqlg/gen/gen_dml.go
- internal/sqlg/gen/gen_methods.go
- internal/util/string.go
- services/configstore/client/client.go
- services/gateway/client/client.go
- services/notification/client/client.go
- services/runservice/client/client.go
Migrate to the new config file version.
Fix new lint errors.
> Update to golangci-lint v2.1.6

- .agola/config.jsonnet
- Dockerfile
- go.mod
* go.mod use go 1.23 minimum version semantics.
* ci: use the current last two go versions: 1.23 and 1.24
* Dockerfile: use go 1.24 image
> *: update to go 1.24
