agola-io/agola

- internal/db/db.go
Since we are using the shared cache with the lock notify we won't receive
SQLITE_BUSY errors but we could receive SQLITE_LOCKED errors due to deadlocks or
locked tables on concurrent read and write transactions.
This patch catches this kind of errors and retries the tx until maxTxRetries.
> db: retry on sqlite locked error

- internal/datamanager/datamanager.go
when datamanager is started in maintenance mode no goroutines are scheduled and
no initial etcd initialization is done
> datamanager: implement maintenance mode

- internal/datamanager/data.go
- internal/datamanager/datamanager_test.go
* export: exports the newest data checkpoint. It forces a checkpoint before
exporting (currently no wals are exported)
* import: cleans up etcd, creates a new datasnaphot from the provided import stream
and then initializes etcd. Currently no old data is removed from the object
storage but it's just ignored.
> datamanager: implement import/export

- .agola/config.jsonnet
- internal/testutil/utils.go
- tests/setup_test.go
Also test clone step so we are sure that the clone url is correct.
> tests: test also clone step

- internal/config/config.go
- internal/runconfig/runconfig.go
- internal/services/gateway/action/run.go
- tests/setup_test.go
Don't create a run if a when condition is defined and it doesn't match.
> config: add run when field

- internal/services/executor/executor.go
Since the current logic is to use the first available private ip address as the
advertized address we have to listen on wildcard since a different host provided
in web.ListenAddress will make the executor unreachable.
In future improve this to let the user to manually define the bind and the
advertized address (perhaps using go-sockaddr templates like done by consul) to
also support nat between the schedulers and the executors.
> executor: listen on wildcard address

- cmd/agola/cmd/directrunstart.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s_test.go
- internal/services/gateway/action/run.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/user.go
- internal/testutil/env.go
- services/gateway/api/types/user.go
- services/gateway/client/client.go
- tests/setup_test.go
Add a --var and --var-file options (repeatable multiple times) to define the
variables to be used in the run.
> userdirectrun: add options to define variables

- internal/services/config/config.go
- internal/services/runservice/common/common.go
- internal/services/runservice/runservice.go
- internal/services/runservice/scheduler.go
- internal/services/runservice/store/store.go
- internal/services/runservice/store/store_test.go
Removes old workspace files (defaults to 7 days)
> runservice: add run workspace cleaner

- internal/services/executor/executor.go
- internal/services/runservice/scheduler.go
- services/runservice/types/types.go
For every step save also the command exit status.
> runservice: save step exitstatus in run.

- internal/services/gateway/api/run.go
- services/gateway/api/types/run.go
For every step return the step type.
For a run step also return the shell and exit status.
> gateway: run api return more step data

- internal/services/executor/executor.go
Add missing mutex unlock that will cause deadlocks.
> executor: add missing mutex unlock

- internal/services/common/secrets.go
- internal/services/gateway/action/secret.go
- internal/services/gateway/api/secret.go
Implement missing removeoverridden option for get secrets.
> gateway: api implement get secrets removeoverridden

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/support.md
> Add github issue templates

- internal/services/gateway/action/project.go
- internal/services/gateway/api/project.go
- services/gateway/api/types/project.go
and make all the request fields optional
> gateway: add parentRef field to project update api

- internal/services/gateway/action/projectgroup.go
- internal/services/gateway/api/projectgroup.go
- services/gateway/api/types/projectgroup.go
and make all the request fields optional
> gateway: add parentRef field to project group update api

- internal/services/gateway/gateway.go
Make it a POST instead of a PUT.
> gateway: fix project create run http method

- services/types/when.go
- services/types/when_test.go
> when: fix typo in tag matching

- internal/gitsources/gitea/gitea.go
Looks like GetRepoRef doesn't correcly handle gitea repo refs response expecting
a single entry. Instead, at least with latest gitea version, the response is
always an array of refs. So use GetRepoRefs.
> gitea: use GetRepoRefs instead of GetRepoRef

- internal/objectstorage/objectstorage_test.go
Test WriteObject using different size values: unspecified, equal to the buffer
size or less than the buffer size.
> objectstorage: add WriteObject tests

- internal/datamanager/data.go
- internal/datamanager/datamanager_test.go
When during a checkpoint more than one file is created the entries position in
the index is not right since it's not reset at every new index.
Fix it and add related tests.
> datamanager: fix index creation on multiple data files

- internal/datamanager/data.go
- internal/datamanager/datamanager.go
- internal/datamanager/datamanager_test.go
- internal/datamanager/wal.go
Remove all wals not required by the existing data status files and not existing
in etcd.
> datamanager: remove old storage wals

- internal/datamanager/data.go
As an optimization don't apply already applied wals.
> datamanager: skip already applied wals in writeDataSnapshot

- internal/services/gateway/api/run.go
- services/gateway/api/types/run.go
A try to add "log_archived" field in "RunTaskResponseStep" (#173).
> gateway: add api to get log status

- internal/services/executor/executor.go
taskUpdater will be called serially and won't block. It'll execute a goroutine
for executing the task and for sending the task state to the scheduler.
executeTask will just start task execution, all the logic of choosing if
starting a task is moved inside taskUpdater
In this way we avoid concurrency issues when handling the same executorTask
in parallel
> executor: serialize task handling

- internal/config/config.go
> config: check max config size

- .agola/config.jsonnet
- Dockerfile
* Update to go 1.14
* Update golangci-lint to v1.23.6 that works with go 1.14
> *: update to go 1.14

- internal/services/runservice/action/action.go
> Remove WaitingApproval for stopped tasks

- internal/git-handler/handler.go
since the git command output is redirected to the http response body, the golang
http server automatically adds a 200 status before sending the body. If the git
command fails we cannot return an http error anymore but must close the
connection to let the client know that the request failed.
> gitserver: fix fetchfile error handling

- internal/services/config/config.go
- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s.go
- internal/services/executor/driver/k8s_test.go
- internal/services/executor/executor.go
- tests/setup_test.go
* Add an executor config option to define the init image to use.
> executor: add config option to define the init image

- internal/services/config/config.go
- internal/services/executor/driver/docker.go
- internal/services/executor/driver/docker_test.go
- internal/services/executor/driver/k8s.go
- internal/services/executor/driver/k8s_test.go
- internal/services/executor/executor.go
Add config options to define docker registry authentication for init image
pulling.
> executor: add init image config authentication options

- internal/gitsources/gitea/gitea.go
Actual implementation doesn't fetch all repository. Gitea API has
pagination.
This patch works wwith gitea pagination for repository listing
Signed-off-by: Yves-Gaël BILLET <yg.billet@gmail.com>
> fix: gitea fetch remote repository with pagination

- go.mod
- go.sum
- internal/services/common/jwt.go
- internal/services/gateway/action/user.go
- internal/services/gateway/gateway.go
- internal/services/gateway/handlers/auth.go
Migrate to the new community maintained version of github.com/dgrijalva/jwt-go
> *: migrate to golang-jwt/jwt

- .agola/config.jsonnet
- internal/testutil/utils.go
- tests/setup_test.go
> ci: update gitea to v1.15.11

- .agola/config.jsonnet
- internal/objectstorage/posix.go
- internal/objectstorage/posixflat.go
- internal/objectstorage/s3.go
- services/runservice/types/types.go
Fix errors reported by new/updated linters
> ci: update golangci-lint to v1.44.2

- internal/config/config.go
- internal/runconfig/runconfig.go
- internal/runconfig/runconfig_test.go
> config: add ability to take the docker registry encoded auth from a variable

- internal/services/gateway/api/run.go
- services/gateway/api/types/run.go
With this PR we want to show all containers images used by the tasks as described in the issue 332.
Can you please review it. Thanks !
> gateway: return task containers image names in RunTaskResponse

- internal/services/executor/executor.go
fix #287
Added the map tasksStarting that contains the tasks that the executor must start but the pod is not already started.
This avoyd conflicts between the tasksUpdaterLoop and podsCleanerLoop
> executor: fix synchronization when pod is starting

- internal/services/gateway/action/project.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/remoterepo.go
Added GetUserGitSource  action to reuse recursive code
> gateway: add GetUserGitSource action to get user gitsource

- internal/services/configstore/action/org.go
- internal/services/configstore/api/org.go
- internal/services/configstore/configstore.go
- internal/services/gateway/action/org.go
- internal/services/gateway/api/org.go
- internal/services/gateway/gateway.go
- services/configstore/api/types/org.go
- services/configstore/client/client.go
- services/gateway/api/types/org.go
- services/gateway/client/client.go
- tests/setup_test.go
Add api PUT /orgs/{orgref} in gateway and configstore to update organization
> *: add api to update organization

- tests/setup_test.go
* Add functional options to define the setup behaviour.
* Provide methods to start/stop/restart agola.
* Wait for all agola components to be stopped.
> tests: improve tests setup

- internal/runconfig/runconfig_test.go
- internal/services/runservice/scheduler_test.go
- tests/setup_test.go
* Remove redundant type declarations
* Fix t.Fatal calls: remove wrong %w and use t.Fatalf
> tests: cleanups

- tests/setup_test.go
Looks like there're some async handlings in gitea when pushing and then instantly creating a pull request that could fail with a 404 Not found.
We tried with a wait, before pr creation, to check that the branch exists but this always returns true also if the pr creation then fails.
So retry the creation for some time on 404.
> tests: fix failing gitea pull request creation

- .agola/config.jsonnet
- Dockerfile
- go.mod
- go.sum
- internal/toolbox/unarchive/unarchive.go
Also update golangci-lint to v1.51.2
> *: update to go 1.20

- .agola/config.jsonnet
- .golangci.yml
- internal/config/config_test.go
- internal/services/configstore/configstore_test.go
- internal/services/runservice/action/action_test.go
- internal/services/runservice/runservice_test.go
- internal/services/runservice/scheduler_test.go
- internal/services/runservice/store/store_test.go
- internal/testutil/utils.go
- tests/setup_test.go
* Parallelize some tests
* Fix getting of free host:port
* Set tests parallelism to 5 in ci tasks
* Enable paralleltest linter
> tests: parallelize tests

- .agola/config.jsonnet
Update docker dind and kaniko images to latest versions
> ci: update images

- internal/gitsources/gitea/gitea.go
- internal/gitsources/gitsource.go
- internal/services/common/gitsource.go
- internal/services/configstore/action/user.go
- internal/services/configstore/api/remotesource.go
- internal/services/configstore/configstore.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/user.go
- services/configstore/client/client.go
- services/gateway/client/client.go
- tests/setup_test.go
* Fix user registration
* use remote source username/password also for user registration
* Fix login logic
* The token value isn't provided on gitea listTokens so the creation logic is wrong. Should check if it works and recreate it if invalid.
* Add tests
> *: Fix auth flow with password based remote source

- cmd/agola/cmd/runlist.go
Fix run list task api call since the api calls were swapped.
> cmd: fix run list task api call

- internal/services/common/db.go
- internal/services/configstore/configstore.go
- internal/services/runservice/runservice.go
- internal/sqlg/manager/manager.go
- internal/sqlg/manager/migrate.go
Define and use a common SetupDB function for all services.
> services: use common SetupDB function

- internal/services/configstore/configstore_test.go
* Use inline functions since they are specific to this test.
* Simplify loops.
* Simplify user and org creation.
> configstore: clean TestOrgInvitation tests

- .agola/config.jsonnet
use a fixed postgres image version (15).
> ci: use fixed postgres image version

- cmd/agola/cmd/userlist.go
- internal/services/configstore/action/user.go
- internal/services/configstore/api/user.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/user.go
- services/configstore/client/client.go
- services/gateway/client/client.go
- tests/setup_test.go
Add cursor fetching to GetUsers api.
> *: add cursor fetching to GetUsers api

- internal/services/configstore/action/user.go
- internal/services/configstore/api/user.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/gateway/action/auth.go
- internal/services/gateway/action/user.go
- internal/services/gateway/api/user.go
- services/configstore/api/types/user.go
- services/configstore/client/client.go
- services/gateway/api/types/user.go
- services/gateway/client/client.go
- tests/setup_test.go
Add cursor fetching to GetUserOrgs api.
> *: add cursor fetching to GetUserOrgs api

- internal/services/configstore/action/org.go
- internal/services/configstore/api/org.go
- internal/services/configstore/configstore.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/gateway/action/org.go
- internal/services/gateway/api/org.go
- services/configstore/client/client.go
- services/gateway/client/client.go
- tests/setup_test.go
Add cursor fetching to GetOrgs api.
> *: add cursor fetching to GetOrgs api

- internal/services/configstore/configstore_test.go
Use a tests matrix like already done in the integration tests.
> configstore: simplify/improve Get tests

- Dockerfile
While the build image was updated in a previous commit, the final image wasn't updated.
> Dockerfile: update final image

- Dockerfile
Create the directories required for the agolademo image.
> Dockerfile: agolademo: create agola directories

- examples/agolademo/docker-compose.yml
> agolademo: fix agolademo image name

- go.mod
- go.sum
- internal/migration/destination/configstore/db/fetch.go
- internal/migration/destination/runservice/db/fetch.go
- internal/services/configstore/db/dml_postgres.go
- internal/services/configstore/db/dml_sqlite3.go
- internal/services/configstore/db/fetch.go
- internal/services/notification/db/dml_postgres.go
- internal/services/notification/db/dml_sqlite3.go
- internal/services/notification/db/fetch.go
- internal/services/runservice/db/dml_postgres.go
- internal/services/runservice/db/dml_sqlite3.go
- internal/services/runservice/db/fetch.go
- internal/sqlg/gen/gen.go
- internal/sqlg/gen/gen_dml.go
- internal/sqlg/gen/gen_fetch.go
- internal/sqlg/gen/gen_methods.go
Use a local copy of ToCamel functions from
github.com/iancoleman/strcase@v0.2.0 since v0.3.0 changed the behavior.
Also keep "ID" all uppercase.
Remove an unneeded append in sqlg gen fetch.
> sqlg updates

- internal/services/configstore/action/org.go
- internal/services/configstore/action/user.go
Using util.NewAPIError(util.KindFromRemoteError, ... on a db error is wrong.
> configstore: fix wrong error handling

- .golangci.yml
- internal/services/gateway/action/action.go
- internal/services/gateway/action/auth.go
- internal/services/gateway/action/badge.go
- internal/services/gateway/action/commitstatusdelivery.go
- internal/services/gateway/action/maintenance.go
- internal/services/gateway/action/org.go
- internal/services/gateway/action/project.go
- internal/services/gateway/action/projectgroup.go
- internal/services/gateway/action/run.go
- internal/services/gateway/action/runwebhookdelivery.go
- internal/services/gateway/action/secret.go
- internal/services/gateway/action/user.go
- internal/services/gateway/action/variable.go
- internal/services/gateway/api/webhook.go
- internal/util/errors.go
add a new helper function to easily convert a RemoteError to an APIError
> gateway: add action.APIErrorFromRemoteError

- internal/services/configstore/action/action.go
- internal/services/configstore/action/org.go
- internal/services/configstore/action/project.go
- internal/services/configstore/action/projectgroup.go
- internal/services/configstore/action/secret.go
- internal/services/configstore/action/user.go
- internal/services/configstore/action/variable.go
- internal/services/configstore/configstore_test.go
- internal/services/configstore/db/db.go
- internal/services/errors/errors.go
- services/gateway/api/errors/errors.go
* Some logic lived in the db package, move it to the action handler.
* Add detailed errors to logic moved from db
> configstore: move logic from db to action handler

- internal/config/config.go
- internal/config/config_test.go
add docker registries auth check since values can be nil
> config: add docker registries auth nil check

- internal/services/gateway/api/run.go
- internal/services/runservice/api/api.go
- internal/util/http.go
* log api: set http Content Type
* http util: set http error Content Type
> api: add some missing http content types headers.

- tests/api_test.go
ProjectCommitStatusRedelivery tests were copied from ProjectRunWebhookRedelivery tests without updating them to use CommitStatus instead of RunWebhook APIs.
> tests: fix wrong ProjectCommitStatusRedelivery test

- internal/services/gateway/api/commitstatusdelivery.go
- internal/services/gateway/api/runwebhookdelivery.go
- services/gateway/client/client.go
- tests/api_test.go
- tests/setup_test.go
add path unescape to projectref url var
> gateway: fix commit status and run webhook deliveries api

- internal/services/gateway/action/project.go
add missing remote error wrapping in action/project.
> gateway: add missing remote error wrapping

- internal/services/config/config.go
- internal/services/config/config_test.go
* Configstore validation was using Runservice db config
* Add missing Notification service db validation
> services/config: fix db config validation

- internal/services/configstore/configstore.go
- internal/services/executor/executor.go
- internal/services/gitserver/main.go
- internal/services/notification/notification.go
- internal/services/runservice/runservice.go
Explicitly create services local directories for dataDir and sqlite3 file path.
> *: explicitly create services local directories
